USERNAME="youruser"
HOSTNAME="archbox"
GPU="amd"        # amd | nvidia | intel | vm
TIMEZONE="Europe/London"
LOCALE="en_GB.UTF-8"
KEYMAP="uk"
INSTALL_BLUETOOTH="true"
INSTALL_SDDM="false"
AUR_HELPER="yay"
